### ISSUE TITLE
Postfix PYTHO 04.12.post2

### ISSUE THREAD

**Issue by debrando** [prometeia/offconda#13]
Backporting dei seguenti commit:
- [x] ... per pytho 4.12.1
- [x] ... per gsf 4.12.2

**Comment by debrando** [comment]
@ilmioalias i pacchetti mi sembrano su, ma a che issue si riferivano?

@loredanaribatto validi tu? Sai quali sono le patch in questione?

Attendo a portare il release branch su beta che questa sia validata...

**Comment by loredanaribatto** [comment]
metto in done per mancato ambiente
