### ISSUE TITLE
Release PYTHO 04.14

### ISSUE THREAD

**Issue by debrando** [prometeia/offconda#19]
- [x] release branch of [gsf 4.14.0](https://github.com/prometeia/gsf/settings/branch_protection_rules/2105397)
- [x] release branch of [pytho 4.14.0](https://github.com/prometeia/pytho/settings/branch_protection_rules/4184401)
- [x] release branch [ratingpro 4.2.1](https://github.com/prometeia/ratingpro/settings/branch_protection_rules/11101937)
- [x] release branch [pytho_docs 4.14.0](https://github.com/prometeia/pytho_docs/settings/branch_protection_rules/11100698)
- [x] release branch simviewer 3.4.1
- [x] installazione in beta
- [x] chiusura milestone https://github.com/prometeia/pytho/milestones/pytho%20v4.14.0
- [x] chiusura milestone  https://github.com/prometeia/gsf/milestones/gsf%20v4.14.0
- [x] chiusura milestone  https://github.com/prometeia/ratingpro/milestones/ratingpro%20v4.2.1
- [x] chiusura milestone  https://github.com/prometeia/pytho_docs/milestones/pytho_docs%20v4.14.0
- [x] chiusura milestone  https://github.com/prometeia/simviewer/milestones/simviewer%20v3.4.1
- [x] rilascio gsf 4.14.0
- [x] rilascio pytho 4.14.0
- [x] rilascio ratingpro 4.2.1
- [x] rilascio pytho_docs 4.14.0
- [x] rilascio simviewer 3.4.1
- [x] rilascio pythokerlib 0.1.1
- [x] rilascio pythokerlib2 0.1.1
- [x] verifica configurazioni e preview delle nuove
- [x] rilascio pacchettone 04.14
- [x] checklist aggiornamento 04.14

**Comment by debrando** [comment]
@loredanaribatto sono online anche gli installar simviewer, riesci a provare il 3.4.1?

**Comment by loredanaribatto** [comment]
Testato eseguibile simviewer
