### ISSUE TITLE
Reach quality gates of code [s1]

### ISSUE THREAD

**Issue by debrando** [prometeia/offconda#27]
- [x] [Simviewer](http://10.102.2.26:9000/dashboard?id=simviewer)
- [x] [PythoKerLib](http://10.102.2.26:9000/dashboard?id=pythokerlib)
- [x] [PythoWeb](http://10.102.2.26:9000/dashboard?id=pytho%3Apytho)
- [x] [GSF](http://10.102.2.26:9000/dashboard?id=pytho%3Agsf)

**Comment by debrando** [comment]
We have some bugs... [QualityProductSoftware_20201119_Pytho.pdf](https://github.com/prometeia/offconda/files/5565647/QualityProductSoftware_20201119_Pytho.pdf)

**Comment by debrando** [comment]
Da sistemare in pytho, @MattiaGianessi ci puoi pensare tu?

![immagine](https://user-images.githubusercontent.com/837632/99647674-65e31d80-2a52-11eb-9f68-c9def4c728c5.png)

**Comment by MattiaGianessi** [comment]
> Da sistemare in pytho, @MattiaGianessi ci puoi pensare tu?
> 
> ![immagine](https://user-images.githubusercontent.com/837632/99647674-65e31d80-2a52-11eb-9f68-c9def4c728c5.png)

get_schema è stato eliminato definitivamente in quanto non utilizzato (la sua funzionalià è stata sostituita da altri strumenti)

**Comment by debrando** [comment]
Il nuovo scan ha rilevato due ulteriori anomalie, che però in develop sembrano sanate. Provo a far girare i test li.

![immagine](https://user-images.githubusercontent.com/837632/99940592-bf0dc280-2d6c-11eb-8e04-20c6e9625074.png)

**Comment by glaucouri** [comment]
vedi:
 https://github.com/prometeia/gsf/issues/720
