### ISSUE TITLE
Revisione Security HotSpot

### ISSUE THREAD

**Issue by debrando** [prometeia/offconda#32]
- [x] pytho develop + official
- [x] gsf develop + official
- [x] simviewer

cfr. http://10.102.2.26:9000/project/issues?id=pyto%3Aweb%3Adev&resolved=false&types=SECURITY_HOTSPOT

**Comment by glaucouri** [comment]
- sistemato il tema della rando.choice con l'aggiunta di una nuova funzione **srand_choice**  che non dovrebbe dar fastidio a sq
- la maggior parte delle altre segnalazioni sono *pwd* o *url* hardcoded, ma nella sezione dei test, revisionati
- Altre segnalazioni arrivano dagli arg degli script di lancio, che nel nostro caso non costituiscono debolezza in quanto script da lanciare in contesto controllato

- rimangono fuori solo un paio di segnalazioni che non ho validato perchè non sono sicuro
